# Generated by Django 3.2.7 on 2021-10-28 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20211028_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='display_image_alt',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
