# Generated by Django 3.2.7 on 2021-11-01 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_display_image_alt'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='introduction',
            field=models.TextField(default='This is the introduction. This will be used as a except on the article_list  page and will be used to break up the images in the posts.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='cover_image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='display_image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
