# Generated by Django 3.2.7 on 2021-11-03 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_article_views'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['pub_date']},
        ),
    ]
